apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app.kubernetes.io/name: step03_app_test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
      nodeport: 33333
