# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-img-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: step03_app_test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: step03_app_test
    spec:
      containers:
      - name: argode-img-container
        image: juhee24/cloud-application:c033737
        envFrom:
        - configMapRef:
            name: prod-env-vars
