apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0
          command: ["redis-server", "/etc/redis/redis.conf"]
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
